### ISSUE TITLE
Types?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [therootcompany/request.js#14]
I'm on a TS project, and I need types for this module.

I don't see anything at https://github.com/DefinitelyTyped/DefinitelyTyped , or in the repo here.

Any advice for getting these types?

**Comment by coolaj86** [comment]
They're in the files. They should be found automatically.

For example:

https://github.com/therootcompany/request.js/blob/main/request.js#L11-L16

https://github.com/therootcompany/request.js/blob/main/request.js#L205-L208

**Comment by coolaj86** [comment]
You also could just use the types from <https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/request-promise> or <https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/request>.

It's the same API.

**Comment by GeoffreyPlitt** [comment]
Thanks!
